# Generated by Django 4.1.7 on 2023-03-30 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointMe", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(blank=True, max_length=30, null=True)),
                ("phone_no", models.CharField(max_length=35)),
                ("date", models.DateField()),
                ("notes", models.CharField(max_length=200)),
            ],
        ),
    ]
