# Generated by Django 4.1.7 on 2023-03-30 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appointMe", "0003_appointment_access_codes"),
    ]

    operations = [
        migrations.RenameField(
            model_name="appointment", old_name="access_codes", new_name="access_code",
        ),
    ]
